---
kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: golang:1.12
    environment:
      GO111MODULE: on
    commands:
      - "go build"
      - "go test"

trigger:
  branch:
  - master
