---
kind: pipeline
type: docker
name: default

steps:
  - name: "install tools"
    image: golang:1.12
    environment:
      GO111MODULE: on
    commands:
      - "make prepare"
      - "make check"
      - "make test"
      - "make build"

trigger:
  branch:
  - master
