language: go

go:
  - 1.12.x

addons:
  ssh_known_hosts: loyso.art

env:
  - GO111MODULE=on

before_install:
  - sudo apt-get install -qq sshpass
  - GO111MODULE=off go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  - export GO111MODULE=on

after_success:
  - echo $STUPID
  - echo -e $SSH_PRIVATE_KEY | base64 --decode > /tmp/id_rsa
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_rsa
  - sshpass -p $SSH_PASS ssh-add /tmp/id_rsa
  - rsync -r --delete-after --quiet bin/fcc root@loyso.art:/usr/local/bin/

notificatins:
  on_success: never