language: go

go:
  - 1.12.x

addons:
  ssh_known_hosts: $(SSH_HOST)

env:
  - GO111MODULE=on

before_install:
  - mkdir /tmp/ssh
  - echo -e $SSH_PRIVATE_KEY | base64 --decode > /tmp/ssh/deploy_key
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/ssh/deploy_key
  - ssh-add /tmp/ssh/deploy_key
  - make prepare
  - make check

install:
  - make deploy

notifications:
  on_success: never
