// Code generated by qtc from "get_info_response.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/templates/get_info_response.qtpl:1
package templates

//line internal/templates/get_info_response.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/templates/get_info_response.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/templates/get_info_response.qtpl:2
type MarshalData struct {
	Revision     string  `json:"revision"`
	Branch       string  `json:"branch"`
	BootTime     string  `json:"boot"`
	Uptime       float64 `json:"uptime"`
	RequestCount int     `json:"request_count"`
}

// JSON marshaling

//line internal/templates/get_info_response.qtpl:13
func (d *MarshalData) StreamJSON(qw422016 *qt422016.Writer) {
//line internal/templates/get_info_response.qtpl:13
	qw422016.N().S(`{"revision":`)
//line internal/templates/get_info_response.qtpl:15
	qw422016.N().Q(d.Revision)
//line internal/templates/get_info_response.qtpl:15
	qw422016.N().S(`,"branch":`)
//line internal/templates/get_info_response.qtpl:16
	qw422016.N().Q(d.Branch)
//line internal/templates/get_info_response.qtpl:16
	qw422016.N().S(`,"boot":`)
//line internal/templates/get_info_response.qtpl:17
	qw422016.N().Q(d.BootTime)
//line internal/templates/get_info_response.qtpl:17
	qw422016.N().S(`,"uptime":`)
//line internal/templates/get_info_response.qtpl:18
	qw422016.N().FPrec(d.Uptime, 0)
//line internal/templates/get_info_response.qtpl:18
	qw422016.N().S(`,"request_count":`)
//line internal/templates/get_info_response.qtpl:19
	qw422016.N().D(d.RequestCount)
//line internal/templates/get_info_response.qtpl:19
	qw422016.N().S(`}`)
//line internal/templates/get_info_response.qtpl:21
	qw422016.N().S(`
`)
//line internal/templates/get_info_response.qtpl:22
}

//line internal/templates/get_info_response.qtpl:22
func (d *MarshalData) WriteJSON(qq422016 qtio422016.Writer) {
//line internal/templates/get_info_response.qtpl:22
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/get_info_response.qtpl:22
	d.StreamJSON(qw422016)
//line internal/templates/get_info_response.qtpl:22
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/get_info_response.qtpl:22
}

//line internal/templates/get_info_response.qtpl:22
func (d *MarshalData) JSON() string {
//line internal/templates/get_info_response.qtpl:22
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/get_info_response.qtpl:22
	d.WriteJSON(qb422016)
//line internal/templates/get_info_response.qtpl:22
	qs422016 := string(qb422016.B)
//line internal/templates/get_info_response.qtpl:22
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/get_info_response.qtpl:22
	return qs422016
//line internal/templates/get_info_response.qtpl:22
}

//line internal/templates/get_info_response.qtpl:25
type NextBus struct {
	Next string `json:"next"`
	Name string `json:"name"`
}

//line internal/templates/get_info_response.qtpl:33
func (d *NextBus) StreamJSON(qw422016 *qt422016.Writer) {
//line internal/templates/get_info_response.qtpl:33
	qw422016.N().S(`{"next":`)
//line internal/templates/get_info_response.qtpl:35
	qw422016.N().Q(d.Next)
//line internal/templates/get_info_response.qtpl:35
	qw422016.N().S(`,"name":`)
//line internal/templates/get_info_response.qtpl:36
	qw422016.N().Q(d.Name)
//line internal/templates/get_info_response.qtpl:36
	qw422016.N().S(`}`)
//line internal/templates/get_info_response.qtpl:38
	qw422016.N().S(`
`)
//line internal/templates/get_info_response.qtpl:39
}

//line internal/templates/get_info_response.qtpl:39
func (d *NextBus) WriteJSON(qq422016 qtio422016.Writer) {
//line internal/templates/get_info_response.qtpl:39
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/get_info_response.qtpl:39
	d.StreamJSON(qw422016)
//line internal/templates/get_info_response.qtpl:39
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/get_info_response.qtpl:39
}

//line internal/templates/get_info_response.qtpl:39
func (d *NextBus) JSON() string {
//line internal/templates/get_info_response.qtpl:39
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/get_info_response.qtpl:39
	d.WriteJSON(qb422016)
//line internal/templates/get_info_response.qtpl:39
	qs422016 := string(qb422016.B)
//line internal/templates/get_info_response.qtpl:39
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/get_info_response.qtpl:39
	return qs422016
//line internal/templates/get_info_response.qtpl:39
}
