// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: communication.proto

package talk

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	_ "github.com/mwitkow/go-proto-validators"
	_ "github.com/gogo/protobuf/gogoproto"
	time "time"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

func (this *Version) Validate() error {
	return nil
}
func (this *ClientInfo) Validate() error {
	if this.DeviceID == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("DeviceID", fmt.Errorf(`value '%v' must not be an empty string`, this.DeviceID))
	}
	if this.APIVersion != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.APIVersion); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("APIVersion", err)
		}
	}
	if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(&(this.BuildTime)); err != nil {
		return github_com_mwitkow_go_proto_validators.FieldError("BuildTime", err)
	}
	if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(&(this.ClientTime)); err != nil {
		return github_com_mwitkow_go_proto_validators.FieldError("ClientTime", err)
	}
	return nil
}
func (this *Approve) Validate() error {
	return nil
}
func (this *Denied) Validate() error {
	return nil
}
func (this *GracefulGoodbye) Validate() error {
	return nil
}
func (this *Ping) Validate() error {
	return nil
}
func (this *Pong) Validate() error {
	return nil
}
func (this *MeasureLatencyRequest) Validate() error {
	return nil
}
func (this *MeasureLatencyResponse) Validate() error {
	return nil
}
